### ISSUE TITLE
Conversion script `datreant_07to1` fails to execute

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant#161]
A fresh installation of `datreant` 1.0.1 yields an error when I try calling `datreant_07to1`:

```
> datreant_07to1 --help
Traceback (most recent call last):
  File "/home/alter/.local/bin/datreant_07to1", line 11, in <module>
    load_entry_point('datreant', 'console_scripts', 'datreant_07to1')()
  File "/home/alter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/alter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/home/alter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/home/alter/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'datreant.scripts.datreant_07to1.main'; 'datreant.scripts.datreant_07to1' is not a package
```
I'm not familiar with the approach we took here for this script; @kain88-de any ideas if there is a quick fix?

**Comment by kain88-de** [comment]
can you import the module in a python interpreter?
