### ISSUE TITLE
Broken with pyparsing 3.x

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant#179]
With `pyparsing` 3.0.7, currently get:

```
>>> import datreant as dtr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.virtualenvs/datreant/lib/python3.9/site-packages/datreant/__init__.py", line 16, in <module>
    from .treants import Treant
  File "/home/david/.virtualenvs/datreant/lib/python3.9/site-packages/datreant/treants.py", line 9, in <module>
    from .collections import Bundle
  File "/home/david/.virtualenvs/datreant/lib/python3.9/site-packages/datreant/collections.py", line 20, in <module>
    from .metadata import Tags, Categories, AggTags, AggCategories
  File "/home/david/.virtualenvs/datreant/lib/python3.9/site-packages/datreant/metadata.py", line 13, in <module>
    from .selectionparser import parse_selection
  File "/home/david/.virtualenvs/datreant/lib/python3.9/site-packages/datreant/selectionparser.py", line 1, in <module>
    from pyparsing import (CaselessLiteral, Word, quotedString,
ImportError: cannot import name 'operatorPrecedence' from 'pyparsing' (/home/david/.virtualenvs/datreant/lib/python3.9/site-packages/pyparsing/__init__.py) 

```

Looks like we may just need to check where these classes have gone in `pyparsing` 3.x.

**Comment by kain88-de** [comment]
Thanks. Can you also do a pupil release?

**Comment by dotsdl** [comment]
Already [up on PyPI](https://pypi.org/project/datreant/)! I have not yet checked the [`conda-forge` recipe](https://github.com/conda-forge/datreant-feedstock/pull/15) for correctness though. Should we update the `pyparsing>=3.0` there as well?

**Comment by dotsdl** [comment]
Just merged conda-forge PR, so we should get this release there shortly.

**Comment by kain88-de** [comment]
Yes
